language: clojure
lein: lein
script: lein test-all
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
branches:
  except:
    - gh-pages
